source 'https://rubygems.org'
ruby '2.1.0'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~>2.0'
gem 'paperclip', github: 'thoughtbot/paperclip'
gem 'aws-sdk'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'railroady'
gem 'xml-simple', :require => 'xmlsimple'
gem 'choice', '~> 0.1.6'
gem 'rails-erd'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0'  
gem 'rubocop', '~> 0.24.1'
gem 'spring'
gem 'bootstrap-sass'
gem 'devise'
gem 'mysql2'
gem 'yard'
gem 'pundit'
gem 'mail_form'
gem 'rspec'
gem 'simple_form'
gem 'better_errors'
gem 'binding_of_caller', :platforms=>[:mri_21]
gem 'quiet_assets'
gem 'rails_layout'
gem 'guard-rspec','~>4.3.1'
gem 'guard','~> 2.8.0'